/**
 * Mock 数据 - SaaS 后台专用
 * 用于开发阶段预览 UI
 */

import type {
  User,
  Device,
  MeasurementRecord,
  DashboardOverview,
  InterventionRule,
  InterventionLog,
  Activity,
  ActivityPushRecord,
  AvailableMetric,
  AvailableAction,
} from './types';
import { mockReportData, mockHistoryReports, generateMockTimeSeriesData } from './mock-data';

// ========== Mock 用户数据 ==========
export const mockUsers: User[] = [
  {
    id: 'user-001',
    tenant_id: 'default-tenant',
    name: '张三',
    gender: 'male',
    age: 35,
    height: 175,
    weight: 70,
    bmi: 22.9,
    tags: ['高压力', '平和质', '焦虑倾向'],
    created_at: '2025-06-15 10:00:00',
    updated_at: '2025-06-19 14:30:00',
  },
  {
    id: 'user-002',
    tenant_id: 'default-tenant',
    name: '李娜',
    gender: 'female',
    age: 28,
    height: 165,
    weight: 55,
    bmi: 20.2,
    tags: ['阴虚质', '疲劳倾向'],
    created_at: '2025-06-14 15:30:00',
    updated_at: '2025-06-19 12:00:00',
  },
  {
    id: 'user-003',
    tenant_id: 'default-tenant',
    name: '王伟',
    gender: 'male',
    age: 42,
    height: 180,
    weight: 85,
    bmi: 26.2,
    tags: ['痰湿质', '高压力', '坐姿不佳'],
    created_at: '2025-06-10 09:00:00',
    updated_at: '2025-06-19 16:00:00',
  },
  {
    id: 'user-004',
    tenant_id: 'default-tenant',
    name: '赵敏',
    gender: 'female',
    age: 31,
    height: 160,
    weight: 48,
    bmi: 18.8,
    tags: ['气虚质', '低压力'],
    created_at: '2025-06-12 11:00:00',
    updated_at: '2025-06-18 17:30:00',
  },
  {
    id: 'user-005',
    tenant_id: 'default-tenant',
    name: '陈刚',
    gender: 'male',
    age: 38,
    height: 172,
    weight: 68,
    bmi: 23.0,
    tags: ['平和质', '睡眠质量差'],
    created_at: '2025-06-08 14:00:00',
    updated_at: '2025-06-19 10:00:00',
  },
];

// ========== Mock 设备数据 ==========
export const mockDevices: Device[] = [
  {
    id: 'device-001',
    code: 'TA0096400014',
    name: '冥想室1号垫',
    model: 'KTS-1000',
    tenant_id: 'default-tenant',
    status: 'online',
    current_user_id: 'user-001',
    current_user: mockUsers[0],
    firmware_version: 'v5.1.2',
    last_online_at: new Date().toISOString(),
    created_at: '2025-06-01 10:00:00',
    updated_at: '2025-06-19 14:00:00',
  },
  {
    id: 'device-002',
    code: 'TA0096400015',
    name: '冥想室2号垫',
    model: 'KTS-1000',
    tenant_id: 'default-tenant',
    status: 'measuring',
    current_user_id: 'user-002',
    current_user: mockUsers[1],
    firmware_version: 'v5.1.2',
    last_online_at: new Date().toISOString(),
    created_at: '2025-06-01 10:00:00',
    updated_at: '2025-06-19 14:30:00',
  },
  {
    id: 'device-003',
    code: 'TA0096400016',
    name: '瑜伽室垫A',
    model: 'KTS-2000',
    tenant_id: 'default-tenant',
    status: 'online',
    firmware_version: 'v5.2.0',
    last_online_at: new Date().toISOString(),
    created_at: '2025-06-05 15:00:00',
    updated_at: '2025-06-19 12:00:00',
  },
  {
    id: 'device-004',
    code: 'TA0096400017',
    name: '瑜伽室垫B',
    model: 'KTS-2000',
    tenant_id: 'default-tenant',
    status: 'offline',
    firmware_version: 'v5.0.8',
    last_online_at: '2025-06-18 20:00:00',
    created_at: '2025-06-05 15:00:00',
    updated_at: '2025-06-18 20:00:00',
  },
  {
    id: 'device-005',
    code: 'TA0096400018',
    name: 'VIP室专用垫',
    model: 'KTS-PRO',
    tenant_id: 'default-tenant',
    status: 'online',
    current_user_id: 'user-003',
    current_user: mockUsers[2],
    firmware_version: 'v5.3.0',
    last_online_at: new Date().toISOString(),
    created_at: '2025-06-10 09:00:00',
    updated_at: '2025-06-19 16:00:00',
  },
];

// ========== Mock Dashboard 数据 ==========
export const mockDashboardOverview: DashboardOverview = {
  tenant_id: 'default-tenant',
  today_measurements: 42,
  today_measurements_trend: 12,
  online_devices: 8,
  total_devices: 12,
  anomaly_rate: 23.5,
  anomaly_rate_trend: -5,
  avg_health_score: 72,
  avg_health_score_trend: 3,
  online_users: 12,
  stress_distribution: {
    relaxed: 35,
    calm: 28,
    focused: 22,
    stressed: 15,
  },
  live_members: [
    {
      user_id: 'user-001',
      user: mockUsers[0],
      device_code: 'TA0096400014',
      started_at: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
      current_metrics: {
        stress_index: 25,
        heart_rate: 68,
        breathing_rate: 14,
      },
      emotion_state: 'relaxed',
      has_alert: false,
    },
    {
      user_id: 'user-002',
      user: mockUsers[1],
      device_code: 'TA0096400015',
      started_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
      current_metrics: {
        stress_index: 45,
        heart_rate: 75,
        breathing_rate: 16,
      },
      emotion_state: 'calm',
      has_alert: false,
    },
    {
      user_id: 'user-003',
      user: mockUsers[2],
      device_code: 'TA0096400018',
      started_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
      current_metrics: {
        stress_index: 82,
        heart_rate: 95,
        breathing_rate: 20,
      },
      emotion_state: 'stressed',
      has_alert: true,
    },
    {
      user_id: 'user-005',
      user: mockUsers[4],
      device_code: 'TA0096400016',
      started_at: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      current_metrics: {
        stress_index: 38,
        heart_rate: 72,
        breathing_rate: 15,
      },
      emotion_state: 'calm',
      has_alert: false,
    },
  ],
  hourly_measurements: [
    { hour: '09:00', count: 5 },
    { hour: '10:00', count: 8 },
    { hour: '11:00', count: 6 },
    { hour: '12:00', count: 3 },
    { hour: '13:00', count: 2 },
    { hour: '14:00', count: 7 },
    { hour: '15:00', count: 9 },
    { hour: '16:00', count: 4 },
    { hour: '17:00', count: 6 },
    { hour: '18:00', count: 5 },
  ],
  daily_trends: [
    { date: '2025-06-13', stress_avg: 38, health_score_avg: 70 },
    { date: '2025-06-14', stress_avg: 42, health_score_avg: 68 },
    { date: '2025-06-15', stress_avg: 35, health_score_avg: 72 },
    { date: '2025-06-16', stress_avg: 45, health_score_avg: 65 },
    { date: '2025-06-17', stress_avg: 40, health_score_avg: 70 },
    { date: '2025-06-18', stress_avg: 38, health_score_avg: 71 },
    { date: '2025-06-19', stress_avg: 42, health_score_avg: 72 },
  ],
};

// ========== Mock 干预规则 ==========
export const mockRules: InterventionRule[] = [
  {
    id: 'rule-001',
    tenant_id: 'default-tenant',
    name: '高压力自动减压',
    description: '当用户压力过高时自动触发减压干预',
    condition_logic: 'AND',
    conditions: [
      { metric: 'stress_index', operator: '>', value: 80 },
      { metric: 'anxiety_index', operator: '>', value: 70 },
    ],
    actions: [
      { type: 'aromatherapy', params: { scent: 'lavender', intensity: 60 } },
      { type: 'light', params: { action: 'dim', brightness: 30, color: 'warm' } },
    ],
    is_enabled: true,
    trigger_count: 23,
    created_at: '2025-06-10 10:00:00',
    updated_at: '2025-06-19 14:30:00',
  },
  {
    id: 'rule-002',
    tenant_id: 'default-tenant',
    name: '疲劳提醒',
    description: '检测到用户疲劳时发送休息提醒',
    condition_logic: 'OR',
    conditions: [
      { metric: 'fatigue_index', operator: '>', value: 60 },
      { metric: 'hrv_score', operator: '<', value: 30 },
    ],
    actions: [
      { type: 'notification', params: { message: '您已疲劳，建议休息' } },
      { type: 'sound', params: { type: 'gentle_bell', volume: 30 } },
    ],
    is_enabled: true,
    trigger_count: 15,
    created_at: '2025-06-12 15:00:00',
    updated_at: '2025-06-18 16:00:00',
  },
  {
    id: 'rule-003',
    tenant_id: 'default-tenant',
    name: '焦虑状态干预',
    description: '当焦虑指数过高时触发镇静干预',
    condition_logic: 'AND',
    conditions: [
      { metric: 'anxiety_index', operator: '>', value: 75 },
      { metric: 'heart_rate', operator: '>', value: 90 },
    ],
    actions: [
      { type: 'aromatherapy', params: { scent: 'chamomile', intensity: 50 } },
      { type: 'light', params: { action: 'dim', brightness: 20, color: 'blue' } },
      { type: 'music', params: { type: 'meditation', volume: 25 } },
    ],
    is_enabled: false,
    trigger_count: 8,
    created_at: '2025-06-15 09:00:00',
    updated_at: '2025-06-17 11:00:00',
  },
];

// ========== Mock 干预日志 ==========
export const mockInterventionLogs: InterventionLog[] = [
  {
    id: 'log-001',
    tenant_id: 'default-tenant',
    rule_id: 'rule-001',
    rule_name: '高压力自动减压',
    user_id: 'user-003',
    user: mockUsers[2],
    triggered_at: '2025-06-19 14:30:00',
    trigger_metrics: {
      stress_index: 82,
      anxiety_index: 75,
      heart_rate: 95,
    },
    actions_executed: [
      { type: 'aromatherapy', params: { scent: 'lavender', intensity: 60 } },
      { type: 'light', params: { action: 'dim', brightness: 30, color: 'warm' } },
    ],
    status: 'success',
    created_at: '2025-06-19 14:30:00',
  },
  {
    id: 'log-002',
    tenant_id: 'default-tenant',
    rule_id: 'rule-002',
    rule_name: '疲劳提醒',
    user_id: 'user-001',
    user: mockUsers[0],
    triggered_at: '2025-06-19 12:15:00',
    trigger_metrics: {
      fatigue_index: 65,
      hrv_score: 28,
    },
    actions_executed: [
      { type: 'notification', params: { message: '您已疲劳，建议休息' } },
    ],
    status: 'success',
    created_at: '2025-06-19 12:15:00',
  },
  {
    id: 'log-003',
    tenant_id: 'default-tenant',
    rule_id: 'rule-001',
    rule_name: '高压力自动减压',
    user_id: 'user-005',
    user: mockUsers[4],
    triggered_at: '2025-06-18 16:45:00',
    trigger_metrics: {
      stress_index: 85,
      anxiety_index: 72,
      heart_rate: 92,
    },
    actions_executed: [
      { type: 'aromatherapy', params: { scent: 'lavender', intensity: 60 } },
    ],
    status: 'success',
    created_at: '2025-06-18 16:45:00',
  },
];

// ========== Mock 活动 ==========
export const mockActivities: Activity[] = [
  {
    id: 'activity-001',
    tenant_id: 'default-tenant',
    title: '周五颂钵音疗',
    type: 'singing_bowl',
    start_time: '2025-06-21 19:00:00',
    end_time: '2025-06-21 20:30:00',
    location: '3楼冥想室',
    max_participants: 15,
    target_tags: ['高压力', '焦虑', '气郁质'],
    description: '通过颂钵的振动频率帮助放松身心，缓解压力和焦虑。',
    status: 'published',
    matched_users: 8,
    pushed_users: 5,
    created_at: '2025-06-18 10:00:00',
    updated_at: '2025-06-19 09:00:00',
  },
  {
    id: 'activity-002',
    tenant_id: 'default-tenant',
    title: '晨间冥想课程',
    type: 'meditation',
    start_time: '2025-06-22 07:00:00',
    end_time: '2025-06-22 08:00:00',
    location: '2楼瑜伽室',
    max_participants: 20,
    target_tags: ['睡眠质量差', '疲劳', '阴虚质'],
    description: '清晨冥想，调节生物钟，改善睡眠质量。',
    status: 'published',
    matched_users: 12,
    pushed_users: 8,
    created_at: '2025-06-19 14:00:00',
    updated_at: '2025-06-19 14:00:00',
  },
  {
    id: 'activity-003',
    tenant_id: 'default-tenant',
    title: '中医体质调理讲座',
    type: 'lecture',
    start_time: '2025-06-25 14:00:00',
    end_time: '2025-06-25 16:00:00',
    location: '1楼会议室',
    max_participants: 30,
    target_tags: ['痰湿质', '气虚质', '阳虚质'],
    description: '邀请中医专家讲解体质调理方法。',
    status: 'draft',
    matched_users: 0,
    pushed_users: 0,
    created_at: '2025-06-19 16:00:00',
    updated_at: '2025-06-19 16:00:00',
  },
];

// ========== Mock 活动推送记录 ==========
export const mockPushRecords: ActivityPushRecord[] = [
  {
    id: 'push-001',
    activity_id: 'activity-001',
    user_id: 'user-001',
    user: mockUsers[0],
    matched_tags: ['高压力'],
    match_reason: '压力指数72>70',
    push_status: 'sent',
    pushed_at: '2025-06-19 10:00:00',
    created_at: '2025-06-19 09:30:00',
  },
  {
    id: 'push-002',
    activity_id: 'activity-001',
    user_id: 'user-003',
    user: mockUsers[2],
    matched_tags: ['高压力'],
    match_reason: '压力指数85>70',
    push_status: 'sent',
    pushed_at: '2025-06-19 10:00:00',
    created_at: '2025-06-19 09:30:00',
  },
  {
    id: 'push-003',
    activity_id: 'activity-001',
    user_id: 'user-005',
    user: mockUsers[4],
    matched_tags: ['睡眠质量差'],
    match_reason: '匹配目标标签',
    push_status: 'pending',
    created_at: '2025-06-19 09:30:00',
  },
];

// ========== 可用指标 ==========
export const mockAvailableMetrics: AvailableMetric[] = [
  { key: 'stress_index', name: '压力敏感度', unit: '%', min: 0, max: 100 },
  { key: 'anxiety_index', name: '焦虑指数', unit: '%', min: 0, max: 100 },
  { key: 'fatigue_index', name: '疲劳指数', unit: '%', min: 0, max: 100 },
  { key: 'heart_rate', name: '心率', unit: 'bpm', min: 40, max: 200 },
  { key: 'hrv_score', name: 'HRV', unit: 'ms', min: 0, max: 100 },
  { key: 'breathing_rate', name: '呼吸频率', unit: '次/分', min: 5, max: 30 },
  { key: 'autonomic_balance', name: '自主神经平衡', unit: '', min: 0, max: 5 },
];

// ========== 可用动作 ==========
export const mockAvailableActions: AvailableAction[] = [
  {
    type: 'aromatherapy',
    name: '🕯️ 香薰机',
    params: [
      {
        key: 'action',
        name: '操作',
        type: 'select',
        options: [
          { value: 'on', label: '开启' },
          { value: 'off', label: '关闭' },
        ],
        default: 'on',
      },
      {
        key: 'scent',
        name: '香型',
        type: 'select',
        options: [
          { value: 'lavender', label: '薰衣草' },
          { value: 'chamomile', label: '洋甘菊' },
          { value: 'sandalwood', label: '檀香' },
          { value: 'eucalyptus', label: '桉树' },
        ],
        default: 'lavender',
      },
      {
        key: 'intensity',
        name: '浓度',
        type: 'number',
        min: 0,
        max: 100,
        default: 50,
      },
    ],
  },
  {
    type: 'light',
    name: '💡 灯光',
    params: [
      {
        key: 'action',
        name: '操作',
        type: 'select',
        options: [
          { value: 'dim', label: '调暗' },
          { value: 'brighten', label: '调亮' },
          { value: 'off', label: '关闭' },
        ],
        default: 'dim',
      },
      {
        key: 'brightness',
        name: '亮度',
        type: 'number',
        min: 0,
        max: 100,
        default: 30,
      },
      {
        key: 'color',
        name: '色温',
        type: 'select',
        options: [
          { value: 'warm', label: '暖光' },
          { value: 'cool', label: '冷光' },
          { value: 'blue', label: '蓝光' },
        ],
        default: 'warm',
      },
    ],
  },
  {
    type: 'music',
    name: '🎵 音乐',
    params: [
      {
        key: 'type',
        name: '类型',
        type: 'select',
        options: [
          { value: 'meditation', label: '冥想音乐' },
          { value: 'nature', label: '自然声音' },
          { value: 'white_noise', label: '白噪音' },
        ],
        default: 'meditation',
      },
      {
        key: 'volume',
        name: '音量',
        type: 'number',
        min: 0,
        max: 100,
        default: 30,
      },
    ],
  },
  {
    type: 'notification',
    name: '🔔 通知',
    params: [
      {
        key: 'message',
        name: '消息内容',
        type: 'text',
        default: '请关注您的身心状态',
      },
    ],
  },
  {
    type: 'sound',
    name: '🔊 提示音',
    params: [
      {
        key: 'type',
        name: '音效',
        type: 'select',
        options: [
          { value: 'gentle_bell', label: '轻柔铃声' },
          { value: 'chime', label: '风铃声' },
          { value: 'gong', label: '铜锣声' },
        ],
        default: 'gentle_bell',
      },
      {
        key: 'volume',
        name: '音量',
        type: 'number',
        min: 0,
        max: 100,
        default: 30,
      },
    ],
  },
];
